### ISSUE TITLE
UX: title of church info hidden

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/religion#15]
Your top centre search box  @potentially hides information. 
![screen shot 2018-07-05 at 4 54 38 pm](https://user-images.githubusercontent.com/26263513/42303485-abc9e948-8075-11e8-8391-0c67e681f8fc.png)

**Comment by neon-ninja** [comment]
Related to https://github.com/Leaflet/Leaflet/issues/4811
