### ISSUE TITLE
UX: line

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/religion#16]
For consistency, I would remove the line between Basemaps and Overlays and increase the gap minimally to the same size gaps you are using between Places of Worship and municipal Buildings.

**Comment by neon-ninja** [comment]
Like this? https://github.com/UoA-eResearch/religion/commit/21fa4b98f280f6092a32660f215d8fbaeb6e3a69

**Comment by DorisAtCeR** [comment]
Sort of, the line is gone, that is good. Now you need to have a gap between the groups for Basemaps and Overlay. Same distance as between Places of Worship and municipal Buildings.

**Comment by neon-ninja** [comment]
Like this? https://github.com/UoA-eResearch/religion/commit/09ce43fa7dd19410f1c42b6aa1950c439ab0b3bc

**Comment by DorisAtCeR** [comment]
All good
