### ISSUE TITLE
UX: Title

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/religion#2]
It would be nice to have titles for both maps that explain what the visualisation is about.

**Comment by neon-ninja** [comment]
The title in each map is at the top of the legend - is this not prominent enough?

**Comment by DorisAtCeR** [comment]
No, typically titles would be at the top centre. Otherwise it appears more like the title of the legend. Moreover, your overall title is smaller than the church titles in the info pop-up boxes. Semantically, the overall title is higher in the hierarchy, hence has to stand out the most.

**Comment by neon-ninja** [comment]
What do you think of https://github.com/UoA-eResearch/religion/commit/68e4bacded1d4e3cdb6f59026b489ef4691341b6 ?

**Comment by DorisAtCeR** [comment]
Yes, I like that.
